language: node_js
os:
  - osx
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - lib32gcc1
matrix:
  include:
    - os: linux
      env: CXX=g++-4.8
      node_js: '7'
    - os: linux
      env: CXX=g++-4.8
      node_js: '6'
    - os: linux
      env: CXX=g++-4.8
      node_js: '5'
    - os: linux
      env: CXX=g++-4.8
      node_js: '4'
