os: unstable

environment:
  matrix:
    - nodejs_version: 7
    - nodejs_version: 6
    - nodejs_version: 5
    - nodejs_version: 4

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install --global npm@latest
  - npm --version
  - npm install

test_script:
  - node --version
  - npm test
